import { Button } from "std-widgets.slint";
import { Empty } from "@project/widget/empty.slint";
import { View } from "@project/widget/view.slint";

export struct ScoreboardItem {
    name: string,
    time: string,
    difficulty: string,
}

export global ScoreboardState {
    in property <[ScoreboardItem]> items;
    property <length> name-size;
    property <length> time-size;
    property <length> difficulty-size;
}

component ScoreboardTitle {
    Text {
        text: "Scoreboard";
        vertical-alignment: TextVerticalAlignment.center;
        horizontal-alignment: TextHorizontalAlignment.center;
    }
}

export component Scoreboard inherits View {
    VerticalLayout {
        padding: 8px;
        alignment: LayoutAlignment.start;
        for item in ScoreboardState.items: Rectangle { }
    }
}
