import { Grid, GridStatus } from "grid.slint";
import { NumberDisplay } from "number_display.slint";
import { FaceButton, FaceButtonStatus } from "face_button.slint";
import { Empty } from "empty.slint";

export { GridStatus, FaceButtonStatus }

export struct GridData {
    x: int,
    y: int,
    status: GridStatus,
}

component BorderHorizontal inherits Image {
    height: 22px;
    horizontal-tiling: repeat;
    source: @image-url("../res/ui/border/border_hor_2x.png");
}

component BorderVertical inherits Image {
    width: 24px;
    vertical-tiling: repeat;
    source: @image-url("../res/ui/border/border_vert_2x.png");
}

component CornerBottomLeft inherits Image {
    width: 24px;
    height: self.width / 24 * 22;
    source: @image-url("../res/ui/border/corner_bottom_left_2x.png");
}

component CornerBottomRight inherits Image {
    width: 24px;
    height: self.width / 24 * 22;
    source: @image-url("../res/ui/border/corner_bottom_right_2x.png");
}

component CornerUpLeft inherits Image {
    width: 24px;
    height: self.width / 24 * 22;
    source: @image-url("../res/ui/border/corner_up_left_2x.png");
}

component CornerUpRight inherits Image {
    width: 24px;
    height: self.width / 24 * 22;
    source: @image-url("../res/ui/border/corner_up_right_2x.png");
}

component TLeft inherits Image {
    width: 24px;
    height: self.width / 24 * 22;
    source: @image-url("../res/ui/border/t_left_2x.png");
}

component TRight inherits Image {
    width: 24px;
    height: self.width / 24 * 22;
    source: @image-url("../res/ui/border/t_right_2x.png");
}

export component Board {
    in-out property <[GridData]> grid-data;
    in property <int> grid-width: 9;
    in property <int> grid-height: 9;
    in property <length> grid-size: 32px;
    callback clicked(x: int, y: int);
    callback pointer-event(x: int, y: int, event: PointerEvent);
    callback hover-changed(x: int, y: int, value: bool);
    callback pressed-changed(x: int, y: int, value: bool);
    in property <int> flag-counter;
    in property <int> time-in-second;
    in property <FaceButtonStatus> face-status;
    callback face_clicked();
    VerticalLayout {
        HorizontalLayout {
            spacing: 0;
            CornerUpLeft { }

            BorderHorizontal { }

            CornerUpRight { }
        }

        HorizontalLayout {
            spacing: 0;
            BorderVertical { }

            Rectangle {
                width: grid-width * grid-size;
                height: 64px;
                background: #444c54;
                HorizontalLayout {
                    alignment: LayoutAlignment.space-between;
                    padding: 6px;
                    NumberDisplay {
                        number: root.flag-counter;
                        width: 82px;
                    }

                    FaceButton {
                        width: 52px;
                        status: root.face-status;
                        clicked => root.face_clicked();
                    }

                    NumberDisplay {
                        number: root.time-in-second;
                        width: 82px;
                    }
                }
            }

            BorderVertical { }
        }

        HorizontalLayout {
            spacing: 0;
            TLeft { }

            BorderHorizontal { }

            TRight { }
        }

        HorizontalLayout {
            spacing: 0;
            BorderVertical { }

            Empty {
                width: grid-width * grid-size;
                height: grid-height * grid-size;
                for data in root.grid-data: Grid {
                    width: grid-size;
                    x: data.x * grid-size;
                    y: data.y * grid-size;
                    status: data.status;
                    clicked => {
                        root.clicked(data.x, data.y)
                    }
                    pointer-event(event) => {
                        root.pointer-event(data.x, data.y, event)
                    }
                    hover-changed(value) => {
                        root.hover-changed(data.x, data.y, value)
                    }
                    pressed-changed(value) => {
                        root.pressed-changed(data.x, data.y, value)
                    }
                }
            }

            BorderVertical { }
        }

        HorizontalLayout {
            spacing: 0;
            CornerBottomLeft { }

            BorderHorizontal { }

            CornerBottomRight { }
        }
    }
}
