import { Digit } from "digit.slint";

export component NumberDisplay {
    in property <int> number;
    width: 82px;
    height: self.width / 41 * 25;
    function int_(number: float) -> int {
        let res: int = number;
        return res;
    }
    Image {
        x: 0;
        y: 0;
        width: parent.width;
        height: parent.height;
        source: @image-url("../res/ui/number/background.svg");
    }

    HorizontalLayout {
        x: root.width / 41 * 2;
        y: root.width / 41 * 2;
        spacing: root.width / 41 * 2;
        Digit {
            width: root.width / 82 * 22;
            number: int_(number / 100);
        }

        Digit {
            width: root.width / 82 * 22;
            number: int_(number / 10) - int_(number / 100) * 10;
        }

        Digit {
            width: root.width / 82 * 22;
            number: number - int_(number / 10) * 10;
        }
    }
}
