import {
    Button,
    Switch,
    Palette,
    HorizontalBox,
} from "std-widgets.slint";
import { Empty } from "@project/widget/empty.slint";
import { ViewName, ViewManagerState } from "@project/logic/view_manager.slint";

// views that need to be controlled from native code
import { Game } from "@project/view/game.slint";
export { GameState } from "@project/view/game.slint";
export { GridData } from "@project/widget/board.slint";
export { GridStatus } from "@project/widget/grid.slint";
import { Scoreboard } from "@project/view/scoreboard.slint";
export { ScoreboardState } from "@project/view/scoreboard.slint";
import { Setting } from "@project/view/setting.slint";
export { SettingState, GameConfig, Difficulty } from "@project/view/setting.slint";

component Debug {
    HorizontalBox {
        for view in [
            ViewName.Game,
            ViewName.Scoreboard,
            ViewName.Setting,
        ]: Button {
            text: "Dbg";
            clicked => {
                ViewManagerState.current-view = view;
            }
        }
    }
}

component TitlebarItem inherits Rectangle {
    in property <string> text;
    callback clicked();
    HorizontalLayout {
        padding: 4px;
        padding-left: 12px;
        padding-right: 12px;
        alignment: LayoutAlignment.center;
        Text {
            text: text;
            font-size: 14px;
            vertical-alignment: TextVerticalAlignment.center;
        }
    }

    _area := TouchArea {
        width: parent.width;
        height: parent.height;
        mouse-cursor: MouseCursor.pointer;
        clicked => {
            clicked();
        }
    }

    states [
        hovered when _area.has-hover: {
            background: #008cff;
        }
    ]
}

export component Entry inherits Window {
    preferred-height: 800px;
    preferred-width: 600px;
    init => {
        Palette.color-scheme = ColorScheme.light
    }
    VerticalLayout {
        HorizontalLayout {
            height: 26px;
            alignment: LayoutAlignment.start;
            TitlebarItem {
                text: "Game";
                clicked => {
                    ViewManagerState.current-view = ViewName.Game;
                }
            }

            TitlebarItem {
                text: "Setting";
                clicked => {
                    ViewManagerState.current-view = ViewName.Setting;
                }
            }

            TitlebarItem {
                text: "Scoreboard";
                clicked => {
                    ViewManagerState.current-view = ViewName.Scoreboard;
                }
            }
        }

        if ViewManagerState.current-view == ViewName.Game:
            Game { }
        if ViewManagerState.current-view == ViewName.Scoreboard:
            Scoreboard { }
        if ViewManagerState.current-view == ViewName.Setting:
            Setting { }
    }
}
