import {
    Button,
    Switch,
    Palette,
    HorizontalBox,
} from "std-widgets.slint";
import { Empty } from "@project/widget/empty.slint";
import { ViewName, ViewManagerState } from "@project/logic/view_manager.slint";

// views that need to be controlled from native code
import { Game } from "@project/view/game.slint";
export { GameState } from "@project/view/game.slint";
import { Scoreboard } from "@project/view/scoreboard.slint";
export { ScoreboardState } from "@project/view/scoreboard.slint";
import { Setting } from "@project/view/setting.slint";
export { SettingState } from "@project/view/setting.slint";

component Debug {
    HorizontalBox {
        for view in [
            ViewName.Game,
            ViewName.Scoreboard,
            ViewName.Setting,
        ]: Button {
            text: "Dbg";
            clicked => {
                ViewManagerState.current-view = view;
            }
        }
    }
}

export component Entry inherits Window {
    preferred-height: 800px;
    preferred-width: 600px;

    init => {
        Palette.color-scheme = ColorScheme.light
    }

    VerticalLayout {
        Debug {
            height: 50px;
        }

        if ViewManagerState.current-view == ViewName.Game:
            Game { }
        if ViewManagerState.current-view == ViewName.Scoreboard:
            Scoreboard { }
        if ViewManagerState.current-view == ViewName.Setting:
            Setting { }
    }
}
